# Generated by Django 4.2.3 on 2023-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
