# Generated by Django 4.2.3 on 2023-07-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menu_appetizer_menu_dessert_menu_main_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='votes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
